In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [47]:
andrew = pd.read_csv('../new_datasets/andrew.csv')
charlie = pd.read_csv('../new_datasets/charlie.csv')
frances = pd.read_csv('../new_datasets/frances.csv')
harvey = pd.read_csv('../new_datasets/harvey.csv')
ike = pd.read_csv('../new_datasets/ike.csv')
irene = pd.read_csv('../new_datasets/irene.csv')
irma = pd.read_csv('../new_datasets/irma.csv')
ivan = pd.read_csv('../new_datasets/ivan.csv')
katrina = pd.read_csv('../new_datasets/katrina.csv')
maria = pd.read_csv('../new_datasets/maria.csv')
matthew = pd.read_csv('../new_datasets/matthew.csv')
michael = pd.read_csv('../new_datasets/michael.csv')
rita = pd.read_csv('../new_datasets/rita.csv')
sandy = pd.read_csv('../new_datasets/sandy.csv')
wilma = pd.read_csv('../new_datasets/wilma.csv')

In [48]:
df_full = pd.concat([andrew, charlie, frances, harvey, ike, irene, irma, ivan, katrina, maria, matthew, michael, rita, sandy, wilma])

In [49]:
df_full

,geoid,area_fips,qtrly_estabs_11_agriculture_forestry_fishing_and_hunting,avg_wkly_wage_11_agriculture_forestry_fishing_and_hunting,month3_emplvl_11_agriculture_forestry_fishing_and_hunting,lq_avg_wkly_wage_11_agriculture_forestry_fishing_and_hunting,lq_qtrly_estabs_11_agriculture_forestry_fishing_and_hunting,lq_month3_emplvl_11_agriculture_forestry_fishing_and_hunting,qtrly_estabs_1024_professional_and_business_services,avg_wkly_wage_1024_professional_and_business_services,...,month3_emplvl_99_unclassified.3,lq_avg_wkly_wage_99_unclassified.3,lq_qtrly_estabs_99_unclassified.3,lq_month3_emplvl_99_unclassified.3,qtrly_estabs_48_49_transportation_and_warehousing.3,avg_wkly_wage_48_49_transportation_and_warehousing.3,month3_emplvl_48_49_transportation_and_warehousing.3,lq_avg_wkly_wage_48_49_transportation_and_warehousing.3,lq_qtrly_estabs_48_49_transportation_and_warehousing.3,lq_month3_emplvl_48_49_transportation_and_warehousing.3
0,Andrew,12011,96.0,299.0,930.0,1.12,0.16,0.17,7227.0,466.0,...,NaN,NaN,NaN,NaN,883.0,441.0,19248.0,0.92,0.85,1.21
1,Andrew,12099,NaN,NaN,NaN,NaN,NaN,NaN,5314.0,548.0,...,NaN,NaN,NaN,NaN,92.0,369.0,714.0,0.93,1.16,0.73
2,Andrew,12087,NaN,NaN,NaN,NaN,NaN,NaN,354.0,470.0,...,NaN,NaN,NaN,NaN,455.0,438.0,4786.0,0.89,0.60,0.42
0,Charlie,12021,98.0,377.0,3947.0,1.01,0.80,3.52,2183.0,676.0,...,226.0,0.87,0.51,0.83,206.0,659.0,1497.0,1.01,0.74,0.36
1,Charlie,12015,21.0,398.0,386.0,1.22,0.50,1.04,589.0,597.0,...,550.0,0.76,0.29,0.41,775.0,640.0,19664.0,0.98,1.00,0.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,Wilma,12099,366.0,510.0,6403.0,1.19,0.70,1.22,10980.0,823.0,...,429.0,0.87,0.66,0.96,369.0,947.0,3628.0,1.46,0.82,0.51
3,Wilma,12071,116.0,471.0,1707.0,1.22,0.60,0.85,3134.0,717.0,...,1173.0,0.93,0.57,0.80,1431.0,708.0,22324.0,0.97,0.93,0.95
4,Wilma,12087,25.0,514.0,90.0,1.46,0.53,0.26,661.0,774.0,...,NaN,NaN,NaN,NaN,5.0,0.0,0.0,0.00,1.24,0.00
5,Wilma,12043,18.0,0.0,0.0,0.00,11.71,0.00,14.0,457.0,...,12.0,0.61,0.17,0.45,20.0,0.0,0.0,0.00,1.03,0.00
6,Wilma,12051,97.0,0.0,0.0,0.00,11.76,0.00,77.0,455.0,...,104.0,0.96,0.39,1.44,141.0,595.0,804.0,1.01,1.38,0.69

In [50]:
df_full.shape

(123, 776)

In [52]:
cost = pd.read_csv("../datasets/other/Client_project_worksheet - Balnce.com impact (2).csv")

In [54]:
df = pd.merge(df_full, cost, left_on=['geoid'], right_on=['name'])

In [38]:
df

,geoid,area_fips,qtrly_estabs_11_agriculture_forestry_fishing_and_hunting,avg_wkly_wage_11_agriculture_forestry_fishing_and_hunting,month3_emplvl_11_agriculture_forestry_fishing_and_hunting,lq_avg_wkly_wage_11_agriculture_forestry_fishing_and_hunting,lq_qtrly_estabs_11_agriculture_forestry_fishing_and_hunting,lq_month3_emplvl_11_agriculture_forestry_fishing_and_hunting,qtrly_estabs_1024_professional_and_business_services,avg_wkly_wage_1024_professional_and_business_services,...,lq_avg_wkly_wage_48_49_transportation_and_warehousing.3,lq_qtrly_estabs_48_49_transportation_and_warehousing.3,lq_month3_emplvl_48_49_transportation_and_warehousing.3,Rank,Name,States,Year,Category,Damage (B$),Damage(Adjusted for Inflation)
0,Andrew,12011,96.0,299.0,930.0,1.12,0.16,0.17,7227.0,466.0,...,0.92,0.85,1.21,6,Andrew,"FL, LA",1992,5,27.0,47.8
1,Andrew,12099,NaN,NaN,NaN,NaN,NaN,NaN,5314.0,548.0,...,0.93,1.16,0.73,6,Andrew,"FL, LA",1992,5,27.0,47.8
2,Andrew,12087,NaN,NaN,NaN,NaN,NaN,NaN,354.0,470.0,...,0.89,0.60,0.42,6,Andrew,"FL, LA",1992,5,27.0,47.8
3,Charlie,12021,98.0,377.0,3947.0,1.01,0.80,3.52,2183.0,676.0,...,1.01,0.74,0.36,12,Charlie,FL,2004,4,16.0,21.1
4,Charlie,12015,21.0,398.0,386.0,1.22,0.50,1.04,589.0,597.0,...,0.98,1.00,0.96,12,Charlie,FL,2004,4,16.0,21.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Wilma,12099,366.0,510.0,6403.0,1.19,0.70,1.22,10980.0,823.0,...,1.46,0.82,0.51,9,Wilma,FL,2005,3,19.0,24.3
119,Wilma,12071,116.0,471.0,1707.0,1.22,0.60,0.85,3134.0,717.0,...,0.97,0.93,0.95,9,Wilma,FL,2005,3,19.0,24.3
120,Wilma,12087,25.0,514.0,90.0,1.46,0.53,0.26,661.0,774.0,...,0.00,1.24,0.00,9,Wilma,FL,2005,3,19.0,24.3
121,Wilma,12043,18.0,0.0,0.0,0.00,11.71,0.00,14.0,457.0,...,0.00,1.03,0.00,9,Wilma,FL,2005,3,19.0,24.3
122,Wilma,12051,97.0,0.0,0.0,0.00,11.76,0.00,77.0,455.0,...,1.01,1.38,0.69,9,Wilma,FL,2005,3,19.0,24.3

In [72]:
df['damage_by_county']=0
for i in df['geoid'].unique():
    count=df[df['geoid']==i].shape[0]
    df.loc[df['geoid']==i,'damage_by_county']=df.loc[df['geoid']==i,'adjusted_damage']*.8/count

In [75]:
df.tail(50)

,geoid,area_fips,qtrly_estabs_11_agriculture_forestry_fishing_and_hunting,avg_wkly_wage_11_agriculture_forestry_fishing_and_hunting,month3_emplvl_11_agriculture_forestry_fishing_and_hunting,lq_avg_wkly_wage_11_agriculture_forestry_fishing_and_hunting,lq_qtrly_estabs_11_agriculture_forestry_fishing_and_hunting,lq_month3_emplvl_11_agriculture_forestry_fishing_and_hunting,qtrly_estabs_1024_professional_and_business_services,avg_wkly_wage_1024_professional_and_business_services,...,lq_qtrly_estabs_48_49_transportation_and_warehousing.3,lq_month3_emplvl_48_49_transportation_and_warehousing.3,rank,name,states,year,category,damage,adjusted_damage,damage_by_county
73,Katrina,22071,13.0,426.0,57.0,1.08,0.09,0.02,2568.0,767.0,...,4.47,4.15,1,Katrina,"FL, LA, MS",2005,3,125.0,160.0,21.333333
74,Katrina,22089,5.0,373.0,16.0,0.77,0.42,0.07,164.0,677.0,...,1.32,1.23,1,Katrina,"FL, LA, MS",2005,3,125.0,160.0,21.333333
75,Katrina,22051,18.0,370.0,78.0,1.03,0.11,0.04,2629.0,620.0,...,1.04,1.69,1,Katrina,"FL, LA, MS",2005,3,125.0,160.0,21.333333
76,Katrina,22103,33.0,461.0,150.0,1.40,0.47,0.22,1129.0,679.0,...,0.94,0.64,1,Katrina,"FL, LA, MS",2005,3,125.0,160.0,21.333333
77,Katrina,22075,13.0,361.0,51.0,0.81,1.32,0.34,99.0,928.0,...,2.60,1.92,1,Katrina,"FL, LA, MS",2005,3,125.0,160.0,21.333333
78,Katrina,22087,2.0,0.0,0.0,0.00,0.14,0.00,145.0,677.0,...,1.74,2.32,1,Katrina,"FL, LA, MS",2005,3,125.0,160.0,21.333333
79,Maria,72013,64.0,0.0,0.0,0.00,5.70,0.00,106.0,423.0,...,0.86,0.44,3,Maria,PR,2017,5,90.0,90.0,14.400000
80,Maria,72025,26.0,0.0,0.0,0.00,1.06,0.00,325.0,526.0,...,0.59,0.56,3,Maria,PR,2017,5,90.0,90.0,14.400000
81,Maria,72021,8.0,0.0,0.0,0.00,0.25,0.00,343.0,397.0,...,0.66,0.32,3,Maria,PR,2017,5,90.0,90.0,14.400000
82,Maria,72127,22.0,0.0,0.0,0.00,0.19,0.00,2520.0,608.0,...,0.62,0.00,3,Maria,PR,2017,5,90.0,90.0,14.400000
83,Maria,72113,45.0,246.0,147.0,0.88,1.91,0.34,266.0,333.0,...,1.37,0.24,3,Maria,PR,2017,5,90.0,90.0,14.400000
84,Matthew,12095,170.0,607.0,2456.0,1.12,0.40,0.33,9923.0,1046.0,...,1.45,1.63,14,Matthew,SE US,2016,1,10.0,10.3,1.177143
85,Matthew,45051,35.0,757.0,214.0,2.02,0.39,0.17,1351.0,707.0,...,0.74,0.42,14,Matthew,SE US,2016,1,10.0,10.3,1.177143
86,Matthew,45019,34.0,455.0,408.0,0.83,0.22,0.17,3108.0,946.0,...,1.34,1.13,14,Matthew,SE US,2016,1,10.0,10.3,1.177143
87,Matthew,45013,22.0,555.0,1442.0,1.23,0.39,2.25,1128.0,852.0,...,0.63,0.46,14,Matthew,SE US,2016,1,10.0,10.3,1.177143
88,Matthew,37129,16.0,0.0,0.0,0.00,0.19,0.00,1673.0,932.0,...,1.11,1.07,14,Matthew,SE US,2016,1,10.0,10.3,1.177143
89,Matthew,37183,71.0,928.0,843.0,1.50,0.20,0.16,9567.0,1220.0,...,0.76,0.35,14,Matthew,SE US,2016,1,10.0,10.3,1.177143
90,Matthew,12031,47.0,635.0,256.0,1.09,0.16,0.05,6254.0,1027.0,...,0.90,0.68,14,Matthew,SE US,2016,1,10.0,10.3,1.177143
91,Michael,12091,16.0,585.0,54.0,1.04,0.23,0.07,1351.0,1244.0,...,0.86,0.39,21,Michael,"FL, GA",2018,5,25.1,25.1,2.868571
92,Michael,12005,27.0,825.0,238.0,1.69,0.45,0.31,974.0,941.0,...,0.90,0.59,21,Michael,"FL, GA",2018,5,25.1,25.1,2.868571
93,Michael,13253,21.0,570.0,343.0,1.38,9.33,15.51,17.0,770.0,...,2.48,0.00,21,Michael,"FL, GA",2018,5,25.1,25.1,2.868571
94,Michael,12037,4.0,0.0,0.0,0.00,1.01,0.00,32.0,736.0,...,0.87,0.18,21,Michael,"FL, GA",2018,5,25.1,25.1,2.868571
95,Michael,12129,11.0,586.0,55.0,1.35,1.94,1.02,72.0,772.0,...,1.26,0.25,21,Michael,"FL, GA",2018,5,25.1,25.1,2.868571
96,Michael,13087,46.0,0.0,0.0,0.00,6.69,0.00,56.0,884.0,...,1.04,0.13,21,Michael,"FL, GA",2018,5,25.1,25.1,2.868571
97,Michael,12045,4.0,0.0,0.0,0.00,0.92,0.00,64.0,665.0,...,1.06,0.00,21,Michael,"FL, GA",2018,5,25.1,25.1,2.868571
98,Rita,22023,4.0,493.0,9.0,1.43,1.51,0.30,23.0,436.0,...,1.18,0.50,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
99,Rita,22001,16.0,594.0,156.0,2.17,1.24,1.12,128.0,707.0,...,4.47,4.15,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
100,Rita,22095,5.0,460.0,47.0,1.13,0.55,0.37,109.0,471.0,...,1.32,1.39,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
101,Rita,22051,18.0,370.0,78.0,1.03,0.11,0.04,2629.0,620.0,...,1.32,1.23,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
102,Rita,22103,33.0,461.0,150.0,1.40,0.47,0.22,1129.0,679.0,...,1.82,1.24,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
103,Rita,48167,14.0,1175.0,40.0,3.08,0.25,0.05,694.0,690.0,...,1.19,0.82,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
104,Rita,22053,17.0,629.0,140.0,2.40,2.14,1.70,79.0,542.0,...,0.94,0.64,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
105,Rita,22075,13.0,361.0,51.0,0.81,1.32,0.34,99.0,928.0,...,1.17,1.17,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
106,Rita,22045,51.0,468.0,406.0,1.28,2.43,1.32,215.0,627.0,...,2.15,2.05,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
107,Rita,48245,44.0,487.0,203.0,1.25,0.67,0.18,831.0,694.0,...,1.06,1.49,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
108,Rita,48201,167.0,560.0,1403.0,1.10,0.16,0.08,17553.0,1006.0,...,5.98,6.18,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
109,Rita,22093,27.0,0.0,0.0,0.00,6.11,0.00,43.0,619.0,...,3.19,1.79,10,Rita,"LA, TX",2005,3,18.5,23.7,1.580000
110,Sandy,36005,4.0,0.0,0.0,0.00,0.02,0.00,1220.0,700.0,...,1.77,3.55,4,Sandy,"NY, NJ, MA",2012,1,65.0,70.2,9.360000
111,Sandy,36119,79.0,708.0,432.0,1.01,0.21,0.11,6690.0,1720.0,...,0.64,0.83,4,Sandy,"NY, NJ, MA",2012,1,65.0,70.2,9.360000
112,Sandy,36081,12.0,0.0,0.0,0.00,0.02,0.00,4787.0,784.0,...,0.78,0.00,4,Sandy,"NY, NJ, MA",2012,1,65.0,70.2,9.360000
113,Sandy,36061,19.0,1181.0,127.0,1.22,0.01,0.01,25508.0,2020.0,...,0.85,0.84,4,Sandy,"NY, NJ, MA",2012,1,65.0,70.2,9.360000
114,Sandy,36059,38.0,600.0,217.0,0.98,0.07,0.04,10113.0,1112.0,...,0.92,0.83,4,Sandy,"NY, NJ, MA",2012,1,65.0,70.2,9.360000
115,Sandy,36103,246.0,660.0,2726.0,1.15,0.46,0.43,9213.0,1063.0,...,0.26,0.00,4,Sandy,"NY, NJ, MA",2012,1,65.0,70.2,9.360000
116,Wilma,12011,127.0,406.0,879.0,0.96,0.19,0.12,14410.0,773.0,...,0.67,0.44,9,Wilma,FL,2005,3,19.0,24.3,2.777143
117,Wilma,12021,102.0,376.0,4699.0,0.92,0.79,3.96,2356.0,748.0,...,0.80,0.35,9,Wilma,FL,2005,3,19.0,24.3,2.777143
118,Wilma,12099,366.0,510.0,6403.0,1.19,0.70,1.22,10980.0,823.0,...,0.82,0.51,9,Wilma,FL,2005,3,19.0,24.3,2.777143
119,Wilma,12071,116.0,471.0,1707.0,1.22,0.60,0.85,3134.0,717.0,...,0.93,0.95,9,Wilma,FL,2005,3,19.0,24.3,2.777143
120,Wilma,12087,25.0,514.0,90.0,1.46,0.53,0.26,661.0,774.0,...,1.24,0.00,9,Wilma,FL,2005,3,19.0,24.3,2.777143
121,Wilma,12043,18.0,0.0,0.0,0.00,11.71,0.00,14.0,457.0,...,1.03,0.00,9,Wilma,FL,2005,3,19.0,24.3,2.777143
122,Wilma,12051,97.0,0.0,0.0,0.00,11.76,0.00,77.0,455.0,...,1.38,0.69,9,Wilma,FL,2005,3,19.0,24.3,2.777143

In [65]:
count

7